- hosts: all
  remote_user: "{{ host_user|default('ubuntu') }}"
  become: yes
  become_method: sudo
  vars_files:
    - "{{ env }}/passwords.yml"
  roles:
    - initial

- hosts: postgres
  remote_user: "{{ app_user }}"
  become: yes
  become_method: sudo
  vars_files:
    - "{{ env }}/passwords.yml"
    - "{{ env }}/settings.yml"
  roles:
    - postgres

- hosts: app
  remote_user: "{{ app_user }}"
  become: yes
  become_method: sudo
  vars_files:
    - "{{ env }}/passwords.yml"
  roles:
    - blog
